CREATE TABLE FactCrashData (
 	crash_id int primary key NOT NULL,
	time_id varchar(50) NOT NULL,
	date_id varchar(50) NOT NULL,
	weather_id varchar(50) NOT NULL,
	location_id varchar(50) NOT NULL,
	event_id varchar(50) NOT NULL,
	total_bike_involved int NOT NULL,
	total_truck_involved int NOT NULL,
	total_heavy_truck_involved int NOT NULL,
	total_motor_cycle_involved int NOT NULL,
	total_other_vehicles_involved int NOT NULL,
	total_pedestrians_involve int NOT NULL,
	FOREIGN KEY (time_id) REFERENCES DimTime(time_id),
	FOREIGN KEY (date_id) REFERENCES DimDate(date_id),
	FOREIGN KEY (weather_id) REFERENCES FactWeather(weather_id),
	FOREIGN KEY (location_id) REFERENCES DimLocation(location_id),
	FOREIGN KEY (event_id) REFERENCES DimEventDesc(event_id),
);
